# Generated by Django 4.2.6 on 2023-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='media/')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'boulder_project_media',
            },
        ),
    ]
