# Generated by Django 4.2.6 on 2023-10-17 14:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='media/'),
        ),
    ]
