# Generated by Django 4.2.6 on 2023-10-26 17:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder_project', '0002_remove_media_url_alter_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
    ]
